### ISSUE TITLE
Features

### ISSUE THREAD

**Issue by cartermw** [dgreif/homebridge-petsafe-smart-feed#12]
I have a service dog in this will be a great addition to my (Small and starting out ) HomeKit!  What features/actions will I be able to do with the home app after I install your plug-in? 

Also could you please tell me about the feeder itself?  Specifically the stainless steel bowl. Is that bowl removal war in 10 I use my own (when one bowl is in the dishwasher)?

Also are there any other smart devices that can receive HomeKit capability besides cameras?

**Comment by dgreif** [comment]
@cartermw sorry for the delayed response.  With this plugin, you can connect your PetSafe smart feeder to HomeKit.  It will provide a switch in HomeKit, which will tell the feeder to feed whatever amount was fed at the previous meal.  

As for the feeder, I couldn't be happier.  They are reliable and do a good job of notifying you when the food is low/empty.  There are some bad reviews about wifi issues, but mine have been 100% reliable in every way. Not positive if a standard bowl will fit in the holder, that's something you would just need to try out.

Not sure exactly what you are referring to with your last question.  There are no camera integrations in this plugin, but there are a large number of homebridge plugins available for almost any smart device you can think of: https://www.npmjs.com/search?q=keywords%3Ahomebridge-plugin
