### ISSUE TITLE
Incorrect Low Battery Warning

### ISSUE THREAD

**Issue by Sunoo** [dgreif/homebridge-petsafe-smart-feed#13]
After a several day long power outage, the Homebridge plugin reports 0% battery, but the official app has it at about 2/3. I’ll try to do more troubleshooting tomorrow after work. I’m also not quite sure why it shows that it is charging in this plugin.

![16F307DC-019D-4691-9FE0-6D57FED527F1](https://user-images.githubusercontent.com/11802168/89609990-665efc00-d847-11ea-85ed-522839c817ff.png)
![D7DDE120-B976-43C8-B8BE-BC82B8E7A743](https://user-images.githubusercontent.com/11802168/89609992-66f79280-d847-11ea-9f1d-d4b1ae27ff9c.png)

**Comment by dgreif** [comment]
Yeah, this one was tough. The smart feed api only provides a voltage, not a percentage, so I had to come up with a calculation for voltage to percentage. Apparently I didn't get it right lol. Would love input if you have any knowledge on the matter

**Comment by Sunoo** [comment]
Ah, that’s annoying, I could potentially try to bust open their Android app and see if I can find the formula they use. Or I could take the easier path and just help capture some data points and try to figure out something that seems reasonable.

**Comment by dgreif** [comment]
Data would be great. Decompiling apks hasn't gotten me great code in the past, but could be worth a try.

**Comment by Sunoo** [comment]
Yea, digging through APKs is a pain, but I may take a crack at it if I have time and motivation. In the meantime, I’ll dump what I’m getting from the API tomorrow some time.

**Comment by dgreif** [comment]
Thanks! I'm glad you got power back 😄

**Comment by Sunoo** [comment]
Thanks!

**Comment by Sunoo** [comment]
Okay, apparently I got distracted for a while there, but I'm back with a little data:

`battery_voltage` is being reported as "26125", the official app still shows 2 of the 3 battery segments filled.

**Comment by dgreif** [comment]
Thanks, good info. I'll try to look into it when I get some time.

**Comment by Sunoo** [comment]
Decided to decompile the Android app, and it looks like I got lucky:

```js
function() {
    var t = this.props.voltage / 32767 * 3.6 * 2;
    return t >= 5.9 ? r(d[11]) : t >= 5.5 ? r(d[12]) : t >= 5 ? r(d[13]) : t >= 0 ? r(d[14]) : void 0
}
```

That's the code to decide which of the four icons to use (full, 2/3, 1/3, empty). `this.props.voltage` matches up with `battery_voltage`.

As a sanity check, I used the value I got from the API with this bit of math and it came back with 5.74, which would put it at the 2/3 icon, as expected.

**Comment by dgreif** [comment]
Amazing!! Thanks for going to that extra effort! Want to throw a pr together? If not, I can do it tomorrow morning with what you gave me.

**Comment by Sunoo** [comment]
Sure thing. I'll get started on that now and will likely have it submitted tomorrow morning.

I also just remembered that it takes 4 batteries, so with `t` in the range of 5-6, that is likely the actual voltage of the batteries.

**Comment by Sunoo** [comment]
I lied about waiting until the morning, PR submitted.
