### ISSUE TITLE
Error message in HB log

### ISSUE THREAD

**Issue by lukebrannon1** [dgreif/homebridge-petsafe-smart-feed#22]
Hello,

I am seeing the following error message in my HB log, and I can no longer trigger the feeder from the Home app. 

`[27/03/2021, 19:27:44] [PetSafeSmartFeed] Failed to reach PetSafe server at https://api.ps-smartfeed.cloud.petsafe.net/api/v2/feeders.  urlToHttpOptions is not a function.  Trying again in 5 seconds...`

My environment:
Homebridge v1.3.4
Node.js v14.15.3
homebridge-petsafe-smart-feed v1.2.6

Any thoughts on how to resolve?

**Comment by dgreif** [comment]
Sorry it's been a while.  I think this was an issue with one of the dependencies.  Are you still seeing this issue on the latest version of the plugin?
