### ISSUE TITLE
Still working for you?

### ISSUE THREAD

**Issue by dcmeglio** [dgreif/homebridge-petsafe-smart-feed#34]
Does this still work for you? I have code I based on yours and recently all I get back is 429 errors when I try to login or query for feeders. I noticed they published a new ios/android app which seems to use a completely different API.

**Comment by dcmeglio** [comment]
When I try to use their old app it seems dead too and just says their cloud service is unavailable.

**Comment by alexanv1** [comment]
I am using a different library (Python with Home Assistant) that uses the same API and running into exactly the same issue including old Android app no longer working. New app works fine but, yes, different API that needs to be reverse-engineered.

429 is "too many requests". Not sure whether they turned off the old API or are simply severely rate-limiting it.

I tried generating a new API token for the old API and token creation succeeded but the very first request with that token failed with 429 as well.

**Comment by dcmeglio** [comment]
Yup. Same experience. Seems the new app will be harder to reverse engineer. They seem to have hired a company that is a bit more professional. The code is obfuscated and they now use ssl certificate pinning so you can’t just setup a proxy. Still doable but much harder. So far I can see they changed the authentication process to make use of AWS Cognito.

**Comment by dgreif** [comment]
Interesting that you are running into issues.  The homebridge plugin is still working and generating new auth tokens without issue.  Because I'm sure I'll need it down the road, I took a look at the new API calls.  Here's the first one, which should help you get started:

```
POST / HTTP1.1
Content-Type: application/x-amz-json-1.1
X-Amz-Target: AWSCognitoIdentityProviderService.InitiateAuth
Accept-Encoding: identity

{
    "AuthFlow": "CUSTOM_AUTH",
    "AuthParameters": {
        "USERNAME": "your.email@somewhere.com",
        "AuthFlow": "CUSTOM_CHALLENGE"
    },
    "ClientId": "18hpp04puqmgf5nc6o474lcp2g"
}
```

There are other headers in the request from the app, but this was enough for me to initiate a token email via postman.  This returns something like the following:

```
{
    "ChallengeName": "CUSTOM_CHALLENGE",
    "ChallengeParameters": {
        "USERNAME": "7e2b7d41-6bf6-4198-b5fd-6ffa406aec3f",
        "attempts": "1"
    },
    "Session": "AYABeCv...very long session...wBEj6SQ"
}
```

You can then do another POST with the USERNAME/Session from that response and the code from the email (using `123456` as an example code here)

```
POST / HTTP1.1
Content-Type: application/x-amz-json-1.1
X-Amz-Target: AWSCognitoIdentityProviderService.RespondToAuthChallenge
Accept-Encoding: identity

{
    "ClientId": "18hpp04puqmgf5nc6o474lcp2g",
    "ChallengeName": "CUSTOM_CHALLENGE",
    "Session": "AYABeCv...very long session...wBEj6SQ",
    "ChallengeResponses": {
        "ANSWER": "123456",
        "USERNAME": "7e2b7d41-6bf6-4198-b5fd-6ffa406aec3f"
    }
}
```

That should give you an auth response that includes the `AccessToken` and a `RefreshToken`.  I haven't explored further than that, but hopefully that gets you started on the right track!

**Comment by dcmeglio** [comment]
Yup I found similar. Doing a little digging they might have added an mqtt connection for real-time notifications instead of having to poll.

**Comment by dcmeglio** [comment]
I'll be working on this this week and will certainly share what I find. No need for us to each re-invent the wheel!

One other thing, this is how you get the cognito URL:

POST to https://directory.cloud.petsafe.net/locale with a body of {"email":"youremail"}

This wil return a json object in part {"data":{"region":"us-east-1"

data.region, is basically pasted into http://cognito-idp.REGIONHERE.amazonaws.com my guess is depending on your locale it might be a different region. For me it's us-east-1

Last thing I think I need to figure out is how to use the refresh token.

**Comment by dcmeglio** [comment]
Refresh token is basically:
POST https://cognito-idp.us-east-1.amazonaws.com/ HTTP/1.1
Host: cognito-idp.us-east-1.amazonaws.com
Content-Type: application/x-amz-json-1.1
X-Amz-Target: AWSCognitoIdentityProviderService.InitiateAuth

{"AuthParameters":{"REFRESH_TOKEN":"refresh_token_value_here"},"AuthFlow":"REFRESH_TOKEN_AUTH","ClientId":"18hpp04puqmgf5nc6o474lcp2g"}

One interesting thing I noticed though is the response body has a new IdToken, but it doesn't give you a new RefreshToken. I'm used to OAuth usually giving you a new refresh token so that the old one doesn't just last forever. Not yet sure if that's a problem or if the refresh token will stop working after a while

**Comment by dgreif** [comment]
@dcmeglio thanks for the additional pointers!  I decided to just hard-code `us-east-1` for now, and will update to track user `email` if I get reports of issues. 

I also found the lack of `REFRESH_TOKEN` in the refresh response a bit troubling.  According to the [AWS Docs](https://docs.aws.amazon.com/cognito/latest/developerguide/amazon-cognito-user-pools-using-the-refresh-token.html), the application owner can extend the life up to 10 years, so hopefully PetSafe has a fairly high life for these tokens 😅.

I've just released v`2.0.0` of the homebridge plugin, which has been updated to use the new API.  Luckily the data structure and API calls didn't really change, so it was mainly just getting the new Cognito auth setup in place.

**Comment by carlosonunez** [comment]
Not an issue, just an observation. PetSafe didn't move _everyone_ onto Cognito. Only new users are being added to the platform. If you're getting `User does not exist` errors from Cognito, try authing with a pre-2.0 version to get the access token, then upgrade.

**Comment by dcmeglio** [comment]
I think there is more to it than just new users. I’ve had my feeder for almost two years but they moved me.
