### ISSUE TITLE
Not able to get access token, get: Error: Cannot find module 'tslib'

### ISSUE THREAD

**Issue by recoi1er** [dgreif/homebridge-petsafe-smart-feed#63]
Attached a screenshot of the entire snippet of what ran after I entered in the line to get the access token and then entered Y for yes.

Hoobs: 4.2.8
Homebridge: 1.5.0
Node: 16.18.1

<img width="1523" alt="image" src="https://user-images.githubusercontent.com/19810634/208963418-3b312cf9-dec1-4665-89fb-39d45293c615.png">

**Comment by dgreif** [comment]
Hmm that's definitely odd. Could you run `npm -v` to see which version of npm you have installed?

As a workaround, you can run `npm i -g ts-lib` to install `ts-lib` globally and then try the `npx` command again

**Comment by recoi1er** [comment]
> Hmm that's definitely odd. Could you run `npm -v` to see which version of npm you have installed?
> 
> As a workaround, you can run `npm i -g ts-lib` to install `ts-lib` globally and then try the `npx` command again

npm -v is 8.19.3

**Comment by dgreif** [comment]
K, that's a fairly recent version so no issues there. Did installing ts-lib globally help?

**Comment by recoi1er** [comment]
It did not work, same error as before! I also updated npm as it told me there was an update for it after installing ts-lib globally

**Comment by recoi1er** [comment]
Wait...it reinstalled the plugin but I am not sure where. I had already installed it within Hoobs

It worked when I put the token into the already installed plugin

**Comment by dgreif** [comment]
`npx` will do a global install of the plugin into your global npm directory (location will vary based on your setup). Sounds like you got it working so I'll go ahead and close this out. If anyone runs into a similar issues with the `npx` command, please let me know.
