### ISSUE TITLE
Cat flap support?

### ISSUE THREAD

**Issue by neinh** [dgreif/homebridge-petsafe-smart-feed#8]
I was wondering if something like that could be done with the CatFlap?
https://www.surepetcare.com/en-gb/pet-doors/microchip-cat-flap-connect

I guess, as they run the same hub, shouldn’t be much different?

**Comment by dgreif** [comment]
Sorry, that CatFlap looks like it is from a completely different company.  The petsafe smart feed does not use a hub, so I highly doubt that they work in a similar way.  Probably something you would need to create a new/separate homebridge plugin for
